### ISSUE TITLE
update error 

### ISSUE THREAD

**Issue by beytullahgol** [tenbaht/sduino#30]
Cannot run program "ln" (in directory "C:\Users\90555\AppData\Local\Arduino15\packages\sduino\hardware\stm8\0.3.2\STM8S_StdPeriph_Driver\src"): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
java.lang.RuntimeException: java.io.IOException: Cannot run program "ln" (in directory "C:\Users\90555\AppData\Local\Arduino15\packages\sduino\hardware\stm8\0.3.2\STM8S_StdPeriph_Driver\src"): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:176)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "ln" (in directory "C:\Users\90555\AppData\Local\Arduino15\packages\sduino\hardware\stm8\0.3.2\STM8S_StdPeriph_Driver\src"): CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at processing.app.Platform.symlink(Platform.java:334)
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:258)
	at cc.arduino.utils.ArchiveExtractor.extract(ArchiveExtractor.java:81)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:159)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:173)
	... 1 more
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 7 more
![update](https://user-images.githubusercontent.com/17261033/32688100-c0ab9388-c6db-11e7-8fbe-a14327648cfc.png)

**Comment by tenbaht** [comment]
Yes, that's right. Again, a symlink slipped into the archive. But the install succeeded nevertheless and the system should be useable. This issue is fixed for 0.3.3 (coming pretty soon, after solving #29)
